### ISSUE TITLE
naming convention

### ISSUE THREAD

**Issue by elianiva** [FlaBBB/WRI#1]
https://github.com/FlaBBB/WRI/blob/16a38ea2ab75046c9b82f33e08ee002249851a66/Beta-Test/day-6/Jobsheet/Prototype/prototype.py#L1

nama class mestinya pake PascalCase

**Comment by FlaBBB** [comment]
ohh oke mas

**Comment by FlaBBB** [comment]
https://github.com/FlaBBB/WRI/commit/8bcf0f87bf4eeb51177cd7ce4dcf553db4089c23

**Comment by FlaBBB** [comment]
#https://github.com/FlaBBB/WRI/commit/8bcf0f87bf4eeb51177cd7ce4dcf553db4089c23
